services:
  cephos_build:
    container_name: cephos_build
    privileged: true
    tty: true
    stdin_open: true
    user: "${CURRENT_UID}:${CURRENT_GID}"
    build:
      context: cephos_build
      args:
        USER_ID: ${CURRENT_UID}
        GROUP_ID: ${CURRENT_GID}
    volumes:
      - ../tmp/work:/home/worker/work
      - ../:/home/worker/project
    environment:
      GITHUB_REF_NAME: ${GITHUB_REF_NAME}
    sysctls:
      net.ipv6.conf.all.disable_ipv6: "0"
    networks:
    - default

networks:
  default:
    driver: bridge
    enable_ipv6: true
