#!/usr/bin/env bash

. /usr/local/lib/cephos/links.sh.lib
. /usr/local/lib/cephos/cephos.sh.lib

log_info "--------------------------------------------------------- boot ---------------------------------------------------------"

log_info "Initialazing..."
check_cephos_is_new_version

log_info "Managing symlinks..."
while IFS= read -r dest_file
do
  [[ "${dest_file:0:1}" == "#" ]] && continue
  ensure_symlink_correct "${dest_file}" "${cephos_root}${dest_file}"
done < /usr/local/share/cephos/init/files

log_info "Managing binds..."
while IFS= read -r dest_dir
do
  [[ "${dest_dir:0:1}" == "#" ]] && continue
  ensure_bind_mount_correct "${dest_dir}" "${cephos_root}${dest_dir}"
done < /usr/local/share/cephos/init/directories

/usr/sbin/modprobe pcspkr || true

exec /sbin/init "$@"
