{
 "title": "CephOS overview",
 "tags": [
  "CephOS",
  "ceph"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(ceph_mon_num_elections,host)"
    }
   },
   {
    "name": "interval",
    "query": "15s,30s,1m,5m,10m,30m,1h,2h,6h,12h,1d"
   },
   {
    "name": "step",
    "query": "15s,30s,1m,5m,10m,30m,1h,2h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  { "title": "Base", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_health_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MON",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(ceph_mon_quorum_status)", "legendFormat": "count" },
    { "expr": "sum(ceph_mon_quorum_status)", "legendFormat": "in" },
    {
     "expr": "sum(ceph_mon_quorum_status == bool 0)",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "OSD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(ceph_osd_metadata)", "legendFormat": "count" },
    { "expr": "sum(ceph_osd_in)", "legendFormat": "in" },
    { "expr": "sum(ceph_osd_in == bool 0)", "legendFormat": "out" },
    { "expr": "sum(ceph_osd_up)", "legendFormat": "up" },
    { "expr": "sum(ceph_osd_up == bool 0)", "legendFormat": "down" }
   ]
  },
  {
   "title": "MGR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(ceph_mgr_status)", "legendFormat": "count" },
    { "expr": "sum(ceph_mgr_status)", "legendFormat": "active" }
   ]
  },
  {
   "title": "MDS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(ceph_mds_metadata)", "legendFormat": "count" },
    { "expr": "count(ceph_mds_request > 0)", "legendFormat": "active" },
    { "expr": "count(ceph_mds_request == 0)", "legendFormat": "hot" }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_cluster_total_bytes", "legendFormat": "total" },
    {
     "expr": "ceph_cluster_total_used_raw_bytes",
     "legendFormat": "used raw"
    },
    {
     "expr": "sum by (pool_id, name) (\n  ceph_pool_max_avail * on(pool_id) group_left(name)\n  ceph_pool_metadata{name=\"storage_data\"}\n)\n+\nsum by (pool_id, name) (\n  ceph_pool_stored * on(pool_id) group_left(name)\n  ceph_pool_metadata{name=\"storage_data\"}\n)",
     "legendFormat": "usable"
    },
    {
     "expr": "sum by (pool_id, name) (\n  ceph_pool_stored * on(pool_id) group_left(name)\n  ceph_pool_metadata{name=~\"storage_.*\"}\n)",
     "legendFormat": "{{ name }} used"
    },
    {
     "expr": "sum by (pool_id, name) (\n  (ceph_pool_compress_under_bytes - ceph_pool_compress_bytes_used) * on(pool_id) group_left(name)\n  ceph_pool_metadata{name=~\"storage_data\"}\n)\n",
     "legendFormat": "compression saved"
    }
   ]
  },
  {
   "title": "PG",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"ceph_pg_.*\"}) by (__name__) > 0",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Health detail",
   "type": "stat",
   "gridPos": { "h": 27, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_health_detail > 0", "legendFormat": "{{ name }}" }
   ]
  },
  {
   "title": "OSD bytes/s in/out",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_in_bytes[$interval]))",
     "legendFormat": "in"
    },
    {
     "expr": "sum(irate(ceph_osd_op_out_bytes[$interval]))",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "OSD latency read/write",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(ceph_osd_op_w_latency_sum[$interval])",
     "legendFormat": "{{ ceph_daemon }} write"
    },
    {
     "expr": "irate(ceph_osd_op_r_latency_sum[$interval])",
     "legendFormat": "{{ ceph_daemon }} read"
    }
   ]
  },
  {
   "title": "OSD bytes used",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_osd_stat_bytes_used", "legendFormat": "{{ ceph_daemon }}" },
    { "expr": "ceph_osd_stat_bytes", "legendFormat": "{{ ceph_daemon }} size" }
   ]
  },
  {
   "title": "OSD recovery rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(ceph_osd_recovery_bytes[$interval])",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "OSD latency apply/commit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "ceph_osd_apply_latency_ms\n", "legendFormat": "{{ ceph_daemon }} apply" },
    { "expr": "ceph_osd_commit_latency_ms", "legendFormat": "{{ ceph_daemon }} commit" }
   ]
  },
  {
   "title": "Storage capacity",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pool_id, name) (\n  ceph_pool_stored * on(pool_id) group_left(name)\n  ceph_pool_metadata{name=~\"storage_.*\"}\n)",
     "legendFormat": "{{ name }} used"
    },
    {
     "expr": "sum by (pool_id, name) (\n  ceph_pool_max_avail * on(pool_id) group_left(name)\n  ceph_pool_metadata{name=~\"storage_data\"}\n)\n+\nsum by (pool_id, name) (\n  ceph_pool_stored * on(pool_id) group_left(name)\n  ceph_pool_metadata{name=~\"storage_data\"}\n)",
     "legendFormat": "{{ name }} max size"
    },
    {
     "expr": "sum by (pool_id, name) (\n  (ceph_pool_compress_under_bytes - ceph_pool_compress_bytes_used) * on(pool_id) group_left(name)\n  ceph_pool_metadata{name=~\"storage_data\"}\n)\n",
     "legendFormat": "{{ name }} compression saved"
    }
   ]
  },
  {
   "title": "MDS operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 2, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(ceph_objecter_op_r{ceph_daemon=~\"mds.*\"}[$interval]) > 0",
     "legendFormat": "{{ host }} MDS reads"
    },
    {
     "expr": "rate(ceph_objecter_op_w{ceph_daemon=~\"mds.*\"}[$interval]) > 0",
     "legendFormat": "{{ host }} MDS writes"
    }
   ]
  },
  {
   "title": "OSD operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r[$interval]) > 0",
     "legendFormat": "{{ host }} {{ ceph_daemon }} reads"
    },
    {
     "expr": "rate(ceph_osd_op_w[$interval]) > 0",
     "legendFormat": "{{ host }} {{ ceph_daemon }} writes"
    }
   ]
  }
 ]
}