#!/bin/bash

set -e

function install_omzsh()
{
  local user_name="$1"
  local user_home="$2"
  git clone https://github.com/ohmyzsh/ohmyzsh.git ${user_home}/.oh-my-zsh
  cp /etc/skel/.zshrc ${user_home}/.zshrc
  chown -R ${user_name}:${user_name} ${user_home}/.oh-my-zsh ${user_home}/.zshrc
  chsh -s /bin/zsh ${user_name}
}

function setup_user()
{
  local user_name="$1"
  local user_pass="$2"

  echo "${user_name}:${user_pass}" | chpasswd
}

users_flag_file="/var/lib/live/config/users.done"
if [ ! -f $users_flag_file ]
then
  root_pw=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 16)
  setup_user "root" "${root_pw}"

  setup_user "cephos" "cephos"
  usermod -aG ceph cephos

  touch $users_flag_file
fi


omz_flag_file="/var/lib/live/config/omz.done"
if [ ! -f $omz_flag_file ]
then
  if curl -s --head --connect-timeout 5 https://github.com >/dev/null
  then
    install_omzsh "root" "/root"
    install_omzsh "cephos" "/home/cephos"
    touch $omz_flag_file
  fi
fi
