#!/bin/bash

. /usr/local/lib/cephos/base.sh.lib
verbose=1

set -e

function install_omzsh()
{
  local user_name="$1"
  local user_home="$2"

  if [ ! -d "${user_home}/.oh-my-zsh" ]
  then
    log_info "Installing oh-my-zsh for user ${user_name}"
    if ! git clone https://github.com/ohmyzsh/ohmyzsh.git ${user_home}/.oh-my-zsh
    then
      log_cry "Failed to download oh-my-zsh for user ${user_name}"
    fi
    cp /etc/skel/.zshrc ${user_home}/.zshrc
    chown -R ${user_name}:${user_name} ${user_home}/.oh-my-zsh ${user_home}/.zshrc
    chsh -s /bin/zsh ${user_name}
  fi
}

flag_file="/var/lib/live/config/omzsh"
if [ ! -f $flag_file ]
then
  log_info "Trying to run script"
  if curl -s --head --connect-timeout 5 https://github.com >/dev/null
  then
    install_omzsh "root" "/root"
    install_omzsh "cephos" "/home/cephos"
    touch $flag_file
  else
    log_err "Network check failed, skipping oh-my-zsh installation"
  fi
fi
