#!/bin/bash

set -e

function install_omzsh()
{
  local user_name="$1"
  local user_home="$2"

  echo "Installing oh-my-zsh for user ${user_name}"
  git clone https://github.com/ohmyzsh/ohmyzsh.git ${user_home}/.oh-my-zsh || { echo "Failed to download oh-my-zsh for user ${user_name}"; exit 1; }
  cp /etc/skel/.zshrc ${user_home}/.zshrc
  chown -R ${user_name}:${user_name} ${user_home}/.oh-my-zsh ${user_home}/.zshrc
  chsh -s /bin/zsh ${user_name}
}

flag_file="/var/lib/live/config/omzsh"
if [ ! -f $flag_file ]
then
  if curl -s --head --connect-timeout 5 https://github.com >/dev/null
  then
    install_omzsh "root" "/root"
    install_omzsh "cephos" "/home/cephos"
    touch $flag_file
  fi
fi
