name: Build installer

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Build with Makefile
        run: make build

      - name: Rename artifact with release tag
        run: |
          TAG=${GITHUB_REF_NAME}
          echo "Using tag: $TAG"
          ls -lh tmp/work/
          mv tmp/work/cephos_installer.run "tmp/work/cephos_installer_${TAG}.run"
          ls -lh tmp/work/

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: tmp/work/cephos_installer_*.run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
