name: Build CephOS installer

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up docker
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Building CephOS
        run: make build

      - name: Rename artifact with release tag
        run: |
          TAG=${GITHUB_REF_NAME}
          echo "Using tag: $TAG"
          ls -lh tmp/work/
          mv tmp/work/cephos_installer.run "tmp/work/cephos_installer_${TAG}.run"
          ls -lh tmp/work/

      # - name: Upload to GitHub Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: ${{ github.event.release.tag_name }}
      #     files: tmp/work/cephos_installer_*.run
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get fresh Access Token from Yandex
        id: get_token
        run: |
          RESPONSE=$(curl -s -X POST https://oauth.yandex.ru/token \
            -d "grant_type=refresh_token" \
            -d "refresh_token=${{ secrets.YANDEX_REFRESH_TOKEN }}" \
            -d "client_id=${{ secrets.YANDEX_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.YANDEX_CLIENT_SECRET }}")
          echo "Received token type: $(echo $RESPONSE | jq -r '.token_type')"
          ACCESS_TOKEN=$(echo $RESPONSE | jq -r '.access_token')
          echo "ACCESS_TOKEN length: ${#ACCESS_TOKEN}"
          echo "::add-mask::$ACCESS_TOKEN"
          echo "token=$ACCESS_TOKEN" >> "$GITHUB_OUTPUT"

      # - name: Debug token output
      #   run: echo "Token is -> ${{ steps.get_token.outputs.token }}" | sed 's/./& /g'

      - name: Get Yandex.Disk upload URL
        id: get_upload_url
        run: |
          TAG=${GITHUB_REF_NAME}
          UPLOAD_URL=$(curl -s \
            -H "Authorization: OAuth ${{ steps.get_token.outputs.token }}" \
            "https://cloud-api.yandex.net/v1/disk/resources/upload?path=GitHub/cephos/cephos_installer_${TAG}.run&overwrite=true" \
            | jq -r '.href')
          if [ "$UPLOAD_URL" == "null" ] || [ -z "$UPLOAD_URL" ]; then
            echo "Failed to get upload URL"
            exit 1
          fi
          echo "upload_url=$UPLOAD_URL" >> "$GITHUB_OUTPUT"

      - name: Upload file to Yandex.Disk
        run: |
          TAG=${GITHUB_REF_NAME}
          curl -T "tmp/work/cephos_installer_${TAG}.run" \
            -o /dev/null \
            --progress-bar \
            "${{ steps.get_upload_url.outputs.upload_url }}"
