name: Build installer

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Build with Makefile
        run: make build

      - name: Rename artifact with release tag
        run: |
          TAG=${GITHUB_REF_NAME}
          ls -lh tmp/work/
          mv tmp/work/cephos_installer.run "tmp/work/cephos_installer_${TAG}.run"

      - name: Upload artifact (workflow artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: cephos_installer
          path: tmp/work/cephos_installer_*.run
