name: Notify on Release

run-name: Release ${{ github.ref_name }} notification (@${{ github.actor }})

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send release information to Telegram
        run: |
          RELEASE_URL="${{ github.event.release.html_url }}"
          TAG="${{ github.event.release.tag_name }}"
          NAME="${{ github.event.release.name }}"

          MESSAGE="🚀 New [Release](${RELEASE_URL}) published. Version: *${TAG}*, Name: ${NAME}"

          curl -s -X POST \
            "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d parse_mode="Markdown" \
            --data-urlencode text="$MESSAGE"
